In [6]:
import numpy as np 

In [9]:
arr = np.array([3,56,54])

In [11]:
print(arr)

[ 3 56 54]


In [12]:
arr.shape 

(3,)

In [13]:
arr[2]=6

In [14]:
print(arr)

[ 3 56  6]


# Array creation: Conversion from other numpy structures

In [18]:
listarray=np .array([[1,2,3], [4,5,6], [7,8,9]])

In [16]:
print(listarray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
listarray.dtype
listarray.shape
listarray.size

9

In [21]:
listarray.dtype

dtype('int64')

In [22]:
listarray.shape

(3, 3)

In [23]:
np.array({34,56,78})

array({56, 34, 78}, dtype=object)

In [46]:
zeros=np.zeros((1,8))

In [47]:
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
rng=np.arange(14)

In [27]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [30]:
lspace = np.linspace(1,35,10)

In [31]:
lspace

array([ 1.        ,  4.77777778,  8.55555556, 12.33333333, 16.11111111,
       19.88888889, 23.66666667, 27.44444444, 31.22222222, 35.        ])

In [32]:
emp=np.empty((4,6))

In [33]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.02360527e-306, 1.60218491e-306, 1.89146896e-307],
       [7.56571288e-307, 3.11525958e-307, 1.24610723e-306,
        1.37962320e-306, 1.29060871e-306, 2.22518251e-306],
       [1.33511969e-306, 1.78022342e-306, 1.05700345e-307,
        3.11525958e-307, 1.69118108e-306, 8.06632139e-308],
       [1.20160711e-306, 1.69119330e-306, 1.29062229e-306,
        6.89804133e-307, 1.11261162e-306, 8.34443015e-308]])

In [34]:
emp_like=np.empty_like(lspace)

In [35]:
emp_like

array([ 1.        ,  4.77777778,  8.55555556, 12.33333333, 16.11111111,
       19.88888889, 23.66666667, 27.44444444, 31.22222222, 35.        ])

In [37]:
ide=np.identity(15)

In [38]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [39]:
ide.shape

(15, 15)

In [40]:
arr=np.arange(99)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [42]:
arr.reshape((3,33))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [43]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [44]:
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [45]:
a3D


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [48]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [49]:
arr=np.array(x)

In [50]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [53]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [54]:
arr.flat

In [58]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [59]:
arr.ndim


2

In [62]:
arr.nbytes


72

In [64]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
arr2 = np.array([[10, 20, 30],
       [42, 5, 6],
       [7, 86, 9]])

In [66]:
arr2

array([[10, 20, 30],
       [42,  5,  6],
       [ 7, 86,  9]])

In [67]:
arr + arr2 

array([[11, 22, 33],
       [46, 10, 12],
       [14, 94, 18]])

In [69]:
arr * arr2

array([[ 10,  40,  90],
       [168,  25,  36],
       [ 49, 688,  81]])

In [70]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [71]:
np.sqrt(arr2)

array([[3.16227766, 4.47213595, 5.47722558],
       [6.4807407 , 2.23606798, 2.44948974],
       [2.64575131, 9.2736185 , 3.        ]])

In [72]:
arr.sum()

np.int64(45)

In [73]:
arr2.sum()

np.int64(215)

In [74]:
arr2.min()

np.int64(5)

In [75]:
arr2.max()

np.int64(86)

In [76]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
type(np.where(arr2>9))

tuple

In [81]:
np.count_nonzero(arr2)

9

In [82]:
np.nonzero(arr2)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))